#!/usr/bin/env python3
import rospy
from garbage_quick_sort_robot_ros.gqsROSMoveIt import GarbageQuickSortRobotROSMoveIt

if __name__=='__main__':
    GarbageQuickSortRobotROSMoveIt()
    rospy.spin()



