#!/usr/bin/env python3
import rospy
from garbage_quick_sort_robot_ros.gqsROSCustomTraj import GarbageQuickSortRobotROSCustomTraj

if __name__=='__main__':
    GarbageQuickSortRobotROSCustomTraj()
    rospy.spin()



