#!/usr/bin/env python3
import rospy
from garbage_quick_sort_robot_ros.gqsROSRoboticsToolbox import GarbageQuickSortRobotROSRoboticsToolbox

if __name__=='__main__':
    GarbageQuickSortRobotROSRoboticsToolbox()
    rospy.spin()



