// Generated by gencpp from file garbage_quick_sort_arduino/target_distance.msg
// DO NOT EDIT!


#ifndef GARBAGE_QUICK_SORT_ARDUINO_MESSAGE_TARGET_DISTANCE_H
#define GARBAGE_QUICK_SORT_ARDUINO_MESSAGE_TARGET_DISTANCE_H

#include <ros/service_traits.h>


#include <garbage_quick_sort_arduino/target_distanceRequest.h>
#include <garbage_quick_sort_arduino/target_distanceResponse.h>


namespace garbage_quick_sort_arduino
{

struct target_distance
{

typedef target_distanceRequest Request;
typedef target_distanceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct target_distance
} // namespace garbage_quick_sort_arduino


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::garbage_quick_sort_arduino::target_distance > {
  static const char* value()
  {
    return "680f8923bb6b23ec7057fffc11ea7b34";
  }

  static const char* value(const ::garbage_quick_sort_arduino::target_distance&) { return value(); }
};

template<>
struct DataType< ::garbage_quick_sort_arduino::target_distance > {
  static const char* value()
  {
    return "garbage_quick_sort_arduino/target_distance";
  }

  static const char* value(const ::garbage_quick_sort_arduino::target_distance&) { return value(); }
};


// service_traits::MD5Sum< ::garbage_quick_sort_arduino::target_distanceRequest> should match
// service_traits::MD5Sum< ::garbage_quick_sort_arduino::target_distance >
template<>
struct MD5Sum< ::garbage_quick_sort_arduino::target_distanceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::garbage_quick_sort_arduino::target_distance >::value();
  }
  static const char* value(const ::garbage_quick_sort_arduino::target_distanceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::garbage_quick_sort_arduino::target_distanceRequest> should match
// service_traits::DataType< ::garbage_quick_sort_arduino::target_distance >
template<>
struct DataType< ::garbage_quick_sort_arduino::target_distanceRequest>
{
  static const char* value()
  {
    return DataType< ::garbage_quick_sort_arduino::target_distance >::value();
  }
  static const char* value(const ::garbage_quick_sort_arduino::target_distanceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::garbage_quick_sort_arduino::target_distanceResponse> should match
// service_traits::MD5Sum< ::garbage_quick_sort_arduino::target_distance >
template<>
struct MD5Sum< ::garbage_quick_sort_arduino::target_distanceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::garbage_quick_sort_arduino::target_distance >::value();
  }
  static const char* value(const ::garbage_quick_sort_arduino::target_distanceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::garbage_quick_sort_arduino::target_distanceResponse> should match
// service_traits::DataType< ::garbage_quick_sort_arduino::target_distance >
template<>
struct DataType< ::garbage_quick_sort_arduino::target_distanceResponse>
{
  static const char* value()
  {
    return DataType< ::garbage_quick_sort_arduino::target_distance >::value();
  }
  static const char* value(const ::garbage_quick_sort_arduino::target_distanceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GARBAGE_QUICK_SORT_ARDUINO_MESSAGE_TARGET_DISTANCE_H
