// Generated by gencpp from file garbage_quick_sort_arduino/target_distanceResponse.msg
// DO NOT EDIT!


#ifndef GARBAGE_QUICK_SORT_ARDUINO_MESSAGE_TARGET_DISTANCERESPONSE_H
#define GARBAGE_QUICK_SORT_ARDUINO_MESSAGE_TARGET_DISTANCERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace garbage_quick_sort_arduino
{
template <class ContainerAllocator>
struct target_distanceResponse_
{
  typedef target_distanceResponse_<ContainerAllocator> Type;

  target_distanceResponse_()
    : distance(0)  {
    }
  target_distanceResponse_(const ContainerAllocator& _alloc)
    : distance(0)  {
  (void)_alloc;
    }



   typedef int32_t _distance_type;
  _distance_type distance;





  typedef boost::shared_ptr< ::garbage_quick_sort_arduino::target_distanceResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::garbage_quick_sort_arduino::target_distanceResponse_<ContainerAllocator> const> ConstPtr;

}; // struct target_distanceResponse_

typedef ::garbage_quick_sort_arduino::target_distanceResponse_<std::allocator<void> > target_distanceResponse;

typedef boost::shared_ptr< ::garbage_quick_sort_arduino::target_distanceResponse > target_distanceResponsePtr;
typedef boost::shared_ptr< ::garbage_quick_sort_arduino::target_distanceResponse const> target_distanceResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::garbage_quick_sort_arduino::target_distanceResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::garbage_quick_sort_arduino::target_distanceResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::garbage_quick_sort_arduino::target_distanceResponse_<ContainerAllocator1> & lhs, const ::garbage_quick_sort_arduino::target_distanceResponse_<ContainerAllocator2> & rhs)
{
  return lhs.distance == rhs.distance;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::garbage_quick_sort_arduino::target_distanceResponse_<ContainerAllocator1> & lhs, const ::garbage_quick_sort_arduino::target_distanceResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace garbage_quick_sort_arduino

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::garbage_quick_sort_arduino::target_distanceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::garbage_quick_sort_arduino::target_distanceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::garbage_quick_sort_arduino::target_distanceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::garbage_quick_sort_arduino::target_distanceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::garbage_quick_sort_arduino::target_distanceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::garbage_quick_sort_arduino::target_distanceResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::garbage_quick_sort_arduino::target_distanceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "680f8923bb6b23ec7057fffc11ea7b34";
  }

  static const char* value(const ::garbage_quick_sort_arduino::target_distanceResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x680f8923bb6b23ecULL;
  static const uint64_t static_value2 = 0x7057fffc11ea7b34ULL;
};

template<class ContainerAllocator>
struct DataType< ::garbage_quick_sort_arduino::target_distanceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "garbage_quick_sort_arduino/target_distanceResponse";
  }

  static const char* value(const ::garbage_quick_sort_arduino::target_distanceResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::garbage_quick_sort_arduino::target_distanceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 distance\n"
;
  }

  static const char* value(const ::garbage_quick_sort_arduino::target_distanceResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::garbage_quick_sort_arduino::target_distanceResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.distance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct target_distanceResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::garbage_quick_sort_arduino::target_distanceResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::garbage_quick_sort_arduino::target_distanceResponse_<ContainerAllocator>& v)
  {
    s << indent << "distance: ";
    Printer<int32_t>::stream(s, indent + "  ", v.distance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GARBAGE_QUICK_SORT_ARDUINO_MESSAGE_TARGET_DISTANCERESPONSE_H
