// Generated by gencpp from file garbage_quick_sort_arduino/target_distanceRequest.msg
// DO NOT EDIT!


#ifndef GARBAGE_QUICK_SORT_ARDUINO_MESSAGE_TARGET_DISTANCEREQUEST_H
#define GARBAGE_QUICK_SORT_ARDUINO_MESSAGE_TARGET_DISTANCEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace garbage_quick_sort_arduino
{
template <class ContainerAllocator>
struct target_distanceRequest_
{
  typedef target_distanceRequest_<ContainerAllocator> Type;

  target_distanceRequest_()
    {
    }
  target_distanceRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::garbage_quick_sort_arduino::target_distanceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::garbage_quick_sort_arduino::target_distanceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct target_distanceRequest_

typedef ::garbage_quick_sort_arduino::target_distanceRequest_<std::allocator<void> > target_distanceRequest;

typedef boost::shared_ptr< ::garbage_quick_sort_arduino::target_distanceRequest > target_distanceRequestPtr;
typedef boost::shared_ptr< ::garbage_quick_sort_arduino::target_distanceRequest const> target_distanceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::garbage_quick_sort_arduino::target_distanceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::garbage_quick_sort_arduino::target_distanceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace garbage_quick_sort_arduino

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::garbage_quick_sort_arduino::target_distanceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::garbage_quick_sort_arduino::target_distanceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::garbage_quick_sort_arduino::target_distanceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::garbage_quick_sort_arduino::target_distanceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::garbage_quick_sort_arduino::target_distanceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::garbage_quick_sort_arduino::target_distanceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::garbage_quick_sort_arduino::target_distanceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::garbage_quick_sort_arduino::target_distanceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::garbage_quick_sort_arduino::target_distanceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "garbage_quick_sort_arduino/target_distanceRequest";
  }

  static const char* value(const ::garbage_quick_sort_arduino::target_distanceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::garbage_quick_sort_arduino::target_distanceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::garbage_quick_sort_arduino::target_distanceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::garbage_quick_sort_arduino::target_distanceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct target_distanceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::garbage_quick_sort_arduino::target_distanceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::garbage_quick_sort_arduino::target_distanceRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // GARBAGE_QUICK_SORT_ARDUINO_MESSAGE_TARGET_DISTANCEREQUEST_H
