#!/usr/bin/env python3
import cv2
import rospy
from cv_bridge import CvBridge, CvBridgeError
from sensor_msgs.msg import Image

cap = cv2.VideoCapture("garbage_3.mp4")
print("Camera Started: ",cap.isOpened(), "\n")

bridge = CvBridge()
image = Image()

def publish_image():
	pub = rospy.Publisher('/garbage_quick_sort/camera/image', Image, queue_size = 10)
	rospy.init_node('image', anonymous = False)
	rate = rospy.Rate(100)

	while not rospy.is_shutdown():
		ret, frame = cap.read()
		if not ret:
			break
		frame = cv2.flip(frame,-1) # 0: vertical flip, 1: horizontal flip, -1: both flip
		msg = bridge.cv2_to_imgmsg(frame, "bgr8")
		image.header.frame_id = "map"
		image.header.stamp = rospy.Time.now()
		image.data = msg
		pub.publish(msg)
		rospy.loginfo("Publishing Image")
		if cv2.waitKey(10) & 0xFF == ord('q'):
			break


if __name__ == '__main__':
	try:
		publish_image()
	except rospy.ROSInterruptException:
		pass
	cap.release()
	cv2.destroyAllWindows()