# Add in the config detail of each dynamixel motor
# Should we add moving speed and compliance....?

# Motor details
# ID 5 is defective

joint_1:
  ID: 3
  Return_Delay_Time: 0
  Baud_Rate: 1
joint_2:
  ID: 8
  Return_Delay_Time: 0
  Baud_Rate: 1
joint_3:
  ID: 1
  Return_Delay_Time: 0
  Baud_Rate: 1
joint_4:
  ID: 4
  Return_Delay_Time: 0
  Baud_Rate: 1
  


